#########################################################
# API Gateway service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
     {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm-charts.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.conatiner.name }}
          image: {{ .Values.image.repository }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configname }}
            - secretRef:
                name: {{ .Values.secretname }}
          env:
            - name: SERVICES
              value: {{ .Values.conatiner.services | join ","}}
---